import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/font.module.scss";
import Topbar from "@/components/Topbar";
import Member from "@/components/Member";
import Message from "@/components/Message";
import groupMockdata from "@/data/groupMockdata";
import chatMockdata from "@/data/chatMockdata";

export default function Subgroup() {
  const sortedChat = chatMockdata.chats
    .slice()
    .sort((a, b) => a.chat_id - b.chat_id);

  return (
    <>
      <Head>
        <title>Group Page</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Topbar />
      <div className="min-h-screen bg-backgroundColor p-12">
        <div className="flex justify-between w-[90%] max-w-7xl px-10 m-auto items-center">
          <div className={`${styles.content} text-3xl font-bold`}>
            Group Name
          </div>
          <div className={`${styles.content} text-2xl font-normal underline`}>
            Leave
          </div>
        </div>
        <div className="flex justify-between w-[90%] max-w-7xl m-auto pt-7 items-start">
          <div className="w-1/4 bg-white rounded-[20px] text-center mr-12 shrink-0">
            <div
              className={`${styles.content} rounded-t-[20px] py-6 text-3xl font-bold bg-secondaryColor`}
            >
              Members
            </div>
            <div className="px-10 pb-10">
              {groupMockdata.users.map((user) => (
                <Member
                  key={user.user_id}
                  picture={user.picture}
                  nickname={user.nickname}
                />
              ))}
            </div>
          </div>
          <div className="w-full rounded-[20px] ">
            <div
              className={`${styles.content} rounded-t-[20px] p-6 text-3xl font-bold text-center bg-secondaryColor`}
            >
              Chat
            </div>
            <div className="flex h-[1200px] rounded-b-[20px] pb-8 bg-white relative justify-center ">
              <div className="w-[90%] h-[1060px] pt-4 overflow-y-scroll">
                {sortedChat.map((chat) => (
                  <Message
                    key={chat.chat_id}
                    message={chat.message}
                    user_id={chat.user_id}
                    sent_at={chat.sent_at}
                    picture={chat.picture}
                    nickname={chat.nickname}
                  />
                ))}
              </div>
              <textarea
                className="w-[90%] h-14 rounded-[20px] bg-backgroundColor pl-6 pr-16 py-3 text-2xl absolute bottom-11"
                placeholder="Leave a message"
              />
              <button type="button">
                <Image
                  src="/send-grey.svg"
                  alt="Send button"
                  className="absolute bottom-14 right-16"
                  width={32}
                  height={32}
                />
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
